# Generated by Django 3.1.4 on 2020-12-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelfentry',
            name='author',
        ),
        migrations.RemoveField(
            model_name='shelfentry',
            name='genre',
        ),
        migrations.AddField(
            model_name='shelfentry',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
