# Generated by Django 3.1.4 on 2020-12-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shelfentry_author'),
        ('main', '0003_favoritegenres'),
    ]

    operations = [
    ]
