# Generated by Django 3.1.4 on 2020-12-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201217_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfentry',
            name='genre',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
