# Generated by Django 3.1.4 on 2020-12-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_shelfentry_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfentry',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
